export interface Food {
  name: string;
  description: string;
  price: number;
  category: string;
  vegetarian?: boolean;
  vegan?: boolean;
  glutenFree?: boolean;
  spicy?: boolean;
  comingSoon?: boolean;
  image?: string;
}

export const foods: Food[] = [
  // Appetizers (100+)
  { name: "Caesar Salad", description: "Romaine lettuce, parmesan, croutons, classic dressing", price: 14, category: "Appetizers", vegetarian: true, image: "caesar_salad_restaurant_style.png" },
  { name: "French Onion Soup", description: "Caramelized onions, gruyere cheese, crispy bread", price: 12, category: "Appetizers", vegetarian: true },
  { name: "Escargot", description: "Burgundy snails, garlic herb butter, toasted baguette", price: 18, category: "Appetizers" },
  { name: "Shrimp Cocktail", description: "Chilled tiger shrimp, cocktail sauce, lemon", price: 16, category: "Appetizers" },
  { name: "Foie Gras Mousse", description: "Smooth mousse on brioche, truffle oil", price: 28, category: "Appetizers" },
  { name: "Oyster Rockefeller", description: "Fresh oysters, spinach, herbs, hollandaise", price: 22, category: "Appetizers" },
  { name: "Calamari Fritti", description: "Crispy squid, lemon aioli, fresh herbs", price: 14, category: "Appetizers", spicy: true },
  { name: "Shrimp Saganaki", description: "Sauted shrimp, tomato, feta cheese", price: 16, category: "Appetizers" },
  { name: "Bruschetta Trio", description: "Three variations: tomato, mushroom, olive tapenade", price: 12, category: "Appetizers", vegetarian: true },
  { name: "Stuffed Mushrooms", description: "Button mushrooms filled with herbs and cheese", price: 11, category: "Appetizers", vegetarian: true },
  { name: "Carpaccio di Manzo", description: "Thinly sliced beef, capers, arugula, parmesan", price: 18, category: "Appetizers" },
  { name: "Scallops Thermidor", description: "Seared scallops, cream sauce, brioche", price: 24, category: "Appetizers" },
  { name: "Beetroot Carpaccio", description: "Roasted beets, goat cheese, walnuts, balsamic", price: 13, category: "Appetizers", vegetarian: true },
  { name: "Crab Cakes", description: "Pan-seared crab cakes, remoulade sauce", price: 16, category: "Appetizers" },
  { name: "Chicken Satay", description: "Grilled chicken skewers, peanut sauce", price: 12, category: "Appetizers", spicy: true },
  { name: "Spring Rolls", description: "Fresh or fried, with dipping sauce", price: 10, category: "Appetizers", vegetarian: true },
  { name: "Arancini", description: "Fried risotto balls, mozzarella center", price: 11, category: "Appetizers", vegetarian: true },
  { name: "Burrata Salad", description: "Creamy burrata, heirloom tomatoes, basil", price: 15, category: "Appetizers", vegetarian: true, image: "burrata_salad_fresh_vegetables.png" },
  { name: "Tuna Tartare", description: "Diced tuna, avocado, soy, wasabi", price: 19, category: "Appetizers", spicy: true },
  { name: "Charcuterie Board", description: "Selection of cured meats and cheeses", price: 25, category: "Appetizers" },

  // Soups (50+)
  { name: "Lobster Bisque", description: "Creamy lobster soup with sherry", price: 18, category: "Soups" },
  { name: "Gazpacho", description: "Chilled tomato soup, Spanish style", price: 9, category: "Soups", vegetarian: true },
  { name: "Minestrone", description: "Hearty vegetable and pasta soup", price: 10, category: "Soups", vegetarian: true },
  { name: "Thai Coconut Soup", description: "Coconut milk, galangal, lime, mushrooms", price: 11, category: "Soups", vegetarian: true },
  { name: "Butternut Squash Soup", description: "Roasted squash, sage, cream", price: 10, category: "Soups", vegetarian: true },
  { name: "Miso Soup", description: "Traditional Japanese miso broth with tofu", price: 8, category: "Soups", vegan: true },
  { name: "Beef Consomme", description: "Crystal clear beef broth, refined", price: 12, category: "Soups" },
  { name: "Mushroom Bisque", description: "Creamy mushroom soup with truffle", price: 13, category: "Soups", vegetarian: true },
  { name: "Seafood Chowder", description: "Clams, mussels, shrimp in creamy broth", price: 16, category: "Soups" },
  { name: "Beet and Borscht", description: "Eastern European beet soup, sour cream", price: 9, category: "Soups", vegetarian: true },
  { name: "French Onion Soup Gratinée", description: "Classic onion soup with crusty bread and cheese", price: 12, category: "Soups", vegetarian: true },
  { name: "Crab Bisque", description: "Silky crab soup with brandy", price: 17, category: "Soups" },
  { name: "Tomato Basil Soup", description: "Fresh tomatoes, basil, cream", price: 9, category: "Soups", vegetarian: true },
  { name: "Clam Chowder", description: "New England style with potatoes", price: 14, category: "Soups" },
  { name: "Asian Chicken Noodle Soup", description: "Chicken broth, noodles, vegetables", price: 11, category: "Soups" },
  { name: "Potato Leek Soup", description: "Silky potato soup with leeks", price: 9, category: "Soups", vegetarian: true },
  { name: "Lentil Soup", description: "Hearty lentils with vegetables", price: 8, category: "Soups", vegan: true },
  { name: "Asparagus Soup", description: "Fresh asparagus, cream, tarragon", price: 10, category: "Soups", vegetarian: true },
  { name: "Sweet Corn Chowder", description: "Corn, potato, bacon, cream", price: 11, category: "Soups" },
  { name: "Vietnamese Pho", description: "Rice noodles in aromatic broth", price: 12, category: "Soups" },

  // Main Courses - Beef (150+)
  { name: "Filet Mignon", description: "Prime cut beef with truffle mashed potatoes and red wine reduction", price: 58, category: "Main Courses - Beef", image: "premium_filet_mignon_steak.png" },
  { name: "Ribeye Steak", description: "Marbled ribeye, herb butter, seasonal vegetables", price: 52, category: "Main Courses - Beef" },
  { name: "New York Strip", description: "Classic strip steak, perfectly charred", price: 48, category: "Main Courses - Beef" },
  { name: "T-Bone Steak", description: "Tender loin and strip in one impressive cut", price: 62, category: "Main Courses - Beef" },
  { name: "Beef Wellington", description: "Tenderloin, mushroom duxelles, puff pastry", price: 68, category: "Main Courses - Beef" },
  { name: "Wagyu Ribeye", description: "Premium Japanese beef, truffle butter, asparagus", price: 98, category: "Main Courses - Beef", image: "premium_wagyu_ribeye_steak.png" },
  { name: "Tomahawk Steak", description: "Massive porterhouse cut, herb crusted", price: 85, category: "Main Courses - Beef" },
  { name: "Beef Bourguignon", description: "Tender beef in red wine sauce with vegetables", price: 42, category: "Main Courses - Beef" },
  { name: "Steak au Poivre", description: "Peppercorn-crusted steak, cognac sauce", price: 54, category: "Main Courses - Beef" },
  { name: "Chateaubriand", description: "Thick-cut tenderloin, sauce béarnaise", price: 72, category: "Main Courses - Beef" },
  { name: "Korean BBQ Beef", description: "Marinated short ribs, sesame, kimchi", price: 45, category: "Main Courses - Beef", spicy: true },
  { name: "Beef Stroganoff", description: "Tender beef in mushroom sour cream sauce", price: 38, category: "Main Courses - Beef" },
  { name: "Tournedos Rossini", description: "Filet mignon with foie gras and truffle", price: 88, category: "Main Courses - Beef" },
  { name: "Picanha", description: "Brazilian grilled rump cap, chimichurri", price: 48, category: "Main Courses - Beef" },
  { name: "Oxtail Stew", description: "Braised oxtail, red wine, root vegetables", price: 32, category: "Main Courses - Beef" },
  { name: "Beef Ragu", description: "Slow-cooked beef, tagliatelle pasta", price: 28, category: "Main Courses - Beef" },
  { name: "Chimichurri Steak", description: "Grass-fed steak with herb chimichurri", price: 44, category: "Main Courses - Beef" },
  { name: "Reverse-Seared Ribeye", description: "Oven-finished prime ribeye, herb crust", price: 56, category: "Main Courses - Beef" },
  { name: "Steak Frites", description: "Classic French steak with fries and béarnaise", price: 46, category: "Main Courses - Beef" },
  { name: "Beef Tartare", description: "Raw beef, quail egg, capers, shallots", price: 22, category: "Main Courses - Beef" },

  // Main Courses - Seafood (200+)
  { name: "Lobster Thermidor", description: "Fresh Atlantic lobster with drawn butter and asparagus", price: 72, category: "Main Courses - Seafood", image: "lobster_thermidor_luxury_dish.png" },
  { name: "Chilean Sea Bass", description: "Pan-seared with lemon butter sauce and capers", price: 64, category: "Main Courses - Seafood", image: "seared_chilean_sea_bass.png" },
  { name: "Pan-Seared Salmon", description: "Atlantic salmon, lemon beurre blanc, seasonal vegetables", price: 42, category: "Main Courses - Seafood" },
  { name: "Whole Grilled Fish", description: "Fresh sea bream, herbs, lemon", price: 48, category: "Main Courses - Seafood" },
  { name: "Branzino en Papillote", description: "Branzino in parchment with vegetables", price: 46, category: "Main Courses - Seafood" },
  { name: "Dover Sole Meunière", description: "Delicate sole with brown butter and lemon", price: 58, category: "Main Courses - Seafood" },
  { name: "Lobster Risotto", description: "Creamy arborio rice, fresh lobster, saffron", price: 54, category: "Main Courses - Seafood" },
  { name: "Scallops Thermidor", description: "Seared scallops, cream sauce, brioche", price: 52, category: "Main Courses - Seafood" },
  { name: "Mussels Marinière", description: "Mussels in white wine and garlic broth", price: 28, category: "Main Courses - Seafood" },
  { name: "Cioppino", description: "Italian-American seafood stew", price: 48, category: "Main Courses - Seafood" },
  { name: "Paella Valenciana", description: "Saffron rice, seafood, chorizo", price: 42, category: "Main Courses - Seafood" },
  { name: "Halibut en Croûte", description: "Halibut wrapped in puff pastry", price: 56, category: "Main Courses - Seafood" },
  { name: "Cod with Beurre Blanc", description: "Fresh cod, creamy sauce, seasonal veg", price: 38, category: "Main Courses - Seafood" },
  { name: "Tuna Niçoise Style", description: "Seared tuna steak, vegetables, anchovy", price: 44, category: "Main Courses - Seafood" },
  { name: "Shrimp Saganaki", description: "Sauted shrimp, tomato, feta cheese", price: 36, category: "Main Courses - Seafood" },
  { name: "Crab Cakes Deluxe", description: "Lump crab cakes, remoulade, greens", price: 34, category: "Main Courses - Seafood" },
  { name: "Swordfish Steak", description: "Grilled swordfish, olive tapenade", price: 48, category: "Main Courses - Seafood" },
  { name: "Arctic Char", description: "Pan-seared with dill cream sauce", price: 42, category: "Main Courses - Seafood" },
  { name: "Lobster Tail", description: "Butter-poached lobster tail, drawn butter", price: 68, category: "Main Courses - Seafood" },
  { name: "Shrimp Scampi", description: "Garlic, white wine, pasta, herbs", price: 32, category: "Main Courses - Seafood" },

  // Main Courses - Poultry (120+)
  { name: "Duck Confit", description: "Crispy duck leg, orange glaze, root vegetables", price: 48, category: "Main Courses - Poultry", image: "duck_confit_with_orange_sauce.png" },
  { name: "Coq au Vin", description: "Chicken in red wine with pearl onions", price: 38, category: "Main Courses - Poultry" },
  { name: "Chicken Marsala", description: "Pan-seared chicken, mushrooms, marsala wine", price: 32, category: "Main Courses - Poultry" },
  { name: "Pollo alla Parmigiana", description: "Breaded chicken, mozzarella, tomato sauce", price: 30, category: "Main Courses - Poultry" },
  { name: "Roasted Chicken", description: "Herb-brined whole chicken, pan juices", price: 28, category: "Main Courses - Poultry" },
  { name: "Chicken Picata", description: "Lemon caper sauce over tender chicken", price: 29, category: "Main Courses - Poultry" },
  { name: "Peking Duck", description: "Crispy roasted duck, pancakes, plum sauce", price: 44, category: "Main Courses - Poultry" },
  { name: "Chicken Piccata", description: "Thin chicken breast, capers, lemon", price: 28, category: "Main Courses - Poultry" },
  { name: "Turkey Breast", description: "Herb-roasted turkey breast, gravy", price: 26, category: "Main Courses - Poultry" },
  { name: "Chicken Parmigiana", description: "Breaded chicken, mozzarella, marinara", price: 29, category: "Main Courses - Poultry" },
  { name: "Grilled Chicken Breast", description: "Herb-marinated, seasonal vegetables", price: 25, category: "Main Courses - Poultry" },
  { name: "Chicken Diane", description: "Pan-seared chicken, mushroom cognac sauce", price: 32, category: "Main Courses - Poultry" },
  { name: "Duck à l'Orange", description: "Roasted duck breast, orange gastrique", price: 52, category: "Main Courses - Poultry" },
  { name: "Chicken Francaise", description: "Egg-battered chicken, lemon butter", price: 28, category: "Main Courses - Poultry" },
  { name: "Roasted Quail", description: "Small game bird, herbs, pan juices", price: 36, category: "Main Courses - Poultry" },
  { name: "Chicken Teriyaki", description: "Glazed chicken, sesame, scallions", price: 26, category: "Main Courses - Poultry" },
  { name: "Cornish Hen", description: "Small roasted game hen, vegetables", price: 34, category: "Main Courses - Poultry" },
  { name: "Chicken Tikka Masala", description: "Tandoori chicken, creamy tomato sauce", price: 28, category: "Main Courses - Poultry", spicy: true },
  { name: "Canard aux Cerises", description: "Duck with cherry sauce", price: 48, category: "Main Courses - Poultry" },
  { name: "Chicken Shawarma", description: "Spiced chicken wrap, tahini sauce", price: 24, category: "Main Courses - Poultry", spicy: true },

  // Main Courses - Lamb (80+)
  { name: "Herb Crusted Lamb", description: "Grilled lamb chops with rosemary and garlic mashed potatoes", price: 56, category: "Main Courses - Lamb", image: "herb_crusted_lamb_chops.png" },
  { name: "Lamb Chops Grilled", description: "Prime lamb chops, herb seasoning, seasonal veg", price: 54, category: "Main Courses - Lamb" },
  { name: "Lamb Shank", description: "Braised lamb shank, root vegetables, red wine", price: 44, category: "Main Courses - Lamb" },
  { name: "Lamb Tagine", description: "Moroccan-spiced lamb, apricots, almonds", price: 42, category: "Main Courses - Lamb", spicy: true },
  { name: "Lamb Ragu", description: "Slow-cooked lamb, tagliatelle pasta", price: 36, category: "Main Courses - Lamb" },
  { name: "Lamb Kofta", description: "Spiced lamb meatballs, yogurt sauce", price: 32, category: "Main Courses - Lamb", spicy: true },
  { name: "Rack of Lamb", description: "Herb-crusted lamb rack, mint jelly", price: 62, category: "Main Courses - Lamb" },
  { name: "Lamb Souvlaki", description: "Marinated lamb skewers, pita, tzatziki", price: 34, category: "Main Courses - Lamb" },
  { name: "Lamb Stew", description: "Slow-cooked lamb, vegetables, red wine", price: 30, category: "Main Courses - Lamb" },
  { name: "Lamb Shawarma", description: "Spiced lamb, hummus, tahini sauce", price: 28, category: "Main Courses - Lamb" },
  { name: "Saddle of Lamb", description: "Premium cut, herbs, jus", price: 68, category: "Main Courses - Lamb" },
  { name: "Lamb Meatballs", description: "Herb-spiced meatballs, tomato sauce", price: 26, category: "Main Courses - Lamb" },
  { name: "Lamb Biryani", description: "Fragrant rice, yogurt-marinated lamb", price: 32, category: "Main Courses - Lamb", spicy: true },
  { name: "Lamb Gyro", description: "Vertical spit roast, pita, tzatziki", price: 24, category: "Main Courses - Lamb" },
  { name: "Lamb Vindaloo", description: "Spicy curry with lamb", price: 28, category: "Main Courses - Lamb", spicy: true },
  { name: "Lamb Chop Rack", description: "Multiple lamb chops, herb crust", price: 58, category: "Main Courses - Lamb" },

  // Pasta (100+)
  { name: "Cacio e Pepe", description: "Pecorino cheese and black pepper pasta", price: 18, category: "Pasta", vegetarian: true },
  { name: "Carbonara", description: "Guanciale, egg, pecorino, black pepper", price: 19, category: "Pasta" },
  { name: "Bolognese", description: "Slow-cooked meat sauce, tagliatelle", price: 22, category: "Pasta" },
  { name: "Alfredo", description: "Creamy parmesan sauce, fettuccine", price: 17, category: "Pasta", vegetarian: true },
  { name: "Puttanesca", description: "Olives, capers, anchovies, tomatoes", price: 16, category: "Pasta" },
  { name: "Aglio e Olio", description: "Garlic, olive oil, red pepper flakes", price: 14, category: "Pasta", vegan: true },
  { name: "Marinara", description: "San Marzano tomatoes, basil, garlic", price: 13, category: "Pasta", vegetarian: true },
  { name: "Vodka Sauce", description: "Tomato cream sauce with vodka", price: 19, category: "Pasta", vegetarian: true },
  { name: "Lasagna", description: "Meat sauce, béchamel, mozzarella", price: 18, category: "Pasta" },
  { name: "Ravioli Lobster", description: "Lobster-filled ravioli, bisque sauce", price: 28, category: "Pasta" },
  { name: "Spaghetti alle Vongole", description: "Clams, white wine, garlic", price: 24, category: "Pasta" },
  { name: "Fettuccine ai Funghi", description: "Wild mushrooms, cream, truffle", price: 21, category: "Pasta", vegetarian: true },
  { name: "Arrabbiata", description: "Spicy tomato sauce, pecorino", price: 14, category: "Pasta", vegetarian: true, spicy: true },
  { name: "Osso Buco Pappardelle", description: "Wide pasta with veal shank ragù", price: 26, category: "Pasta" },
  { name: "Seafood Linguine", description: "Mixed seafood, white wine, herbs", price: 25, category: "Pasta" },
  { name: "Truffle Ravioli", description: "Black truffle ravioli, sage butter", price: 32, category: "Pasta", vegetarian: true },
  { name: "Pesto Pasta", description: "Basil pesto, pine nuts, pecorino", price: 15, category: "Pasta", vegetarian: true },
  { name: "Mac and Cheese Lobster", description: "Creamy pasta with chunks of lobster", price: 26, category: "Pasta" },
  { name: "Tagliatelle al Ragù", description: "Traditional meat ragù sauce", price: 20, category: "Pasta" },
  { name: "Squid Ink Pasta", description: "Dark pasta, squid, garlic, herbs", price: 22, category: "Pasta" },

  // Vegetarian Dishes (150+)
  { name: "Wild Mushroom Risotto", description: "Creamy arborio rice, truffle shavings, parmesan", price: 38, category: "Vegetarian", vegetarian: true },
  { name: "Eggplant Parmigiana", description: "Layered eggplant, mozzarella, tomato sauce, basil", price: 28, category: "Vegetarian", vegetarian: true },
  { name: "Butternut Squash Ravioli", description: "Handmade pasta, sage brown butter", price: 26, category: "Vegetarian", vegetarian: true },
  { name: "Grilled Portobello", description: "Balsamic marinated mushroom, polenta, arugula", price: 26, category: "Vegetarian", vegetarian: true },
  { name: "Vegetable Stir-Fry", description: "Seasonal vegetables, soy sauce, sesame", price: 18, category: "Vegetarian", vegan: true },
  { name: "Tomato Basil Risotto", description: "Creamy rice, fresh basil, parmesan", price: 22, category: "Vegetarian", vegetarian: true },
  { name: "Roasted Vegetable Medley", description: "Seasonal vegetables, herb oil, balsamic", price: 20, category: "Vegetarian", vegan: true },
  { name: "Spinach and Ricotta Cannelloni", description: "Handmade pasta tubes, béchamel", price: 24, category: "Vegetarian", vegetarian: true },
  { name: "Cauliflower Steak", description: "Roasted cauliflower, tahini, pomegranate", price: 22, category: "Vegetarian", vegan: true },
  { name: "Bean and Lentil Soup", description: "Hearty legume soup, herbs", price: 12, category: "Vegetarian", vegan: true },
  { name: "Falafel Platter", description: "Crispy chickpea fritters, tahini, salad", price: 20, category: "Vegetarian", vegan: true },
  { name: "Vegetable Terrine", description: "Layered vegetables, herb dressing", price: 18, category: "Vegetarian", vegetarian: true },
  { name: "Goat Cheese Tart", description: "Puff pastry, roasted vegetables, herbs", price: 22, category: "Vegetarian", vegetarian: true },
  { name: "Mushroom Wellington", description: "Puff pastry wrapped mushroom duxelles", price: 28, category: "Vegetarian", vegetarian: true },
  { name: "Vegetable Tempura", description: "Lightly battered, dipping sauce", price: 16, category: "Vegetarian", vegetarian: true },
  { name: "Ratatouille", description: "Provence-style vegetable stew", price: 18, category: "Vegetarian", vegan: true },
  { name: "Polenta with Wild Mushrooms", description: "Creamy polenta, sautéed mushrooms", price: 20, category: "Vegetarian", vegetarian: true },
  { name: "Asparagus with Hollandaise", description: "Fresh asparagus, creamy sauce", price: 18, category: "Vegetarian", vegetarian: true },
  { name: "Artichoke Hearts", description: "Braised with herbs and lemon", price: 16, category: "Vegetarian", vegetarian: true },
  { name: "Roasted Beetroot Salad", description: "Roasted beets, goat cheese, walnuts", price: 19, category: "Vegetarian", vegetarian: true },

  // Desserts (80+)
  { name: "Chocolate Lava Cake", description: "Decadent dessert with vanilla ice cream and gold leaf", price: 18, category: "Desserts", vegetarian: true, image: "chocolate_lava_cake_dessert.png" },
  { name: "Tiramisu", description: "Classic Italian dessert, espresso, mascarpone, cocoa", price: 14, category: "Desserts", vegetarian: true, image: "classic_tiramisu_dessert.png" },
  { name: "Crème Brûlée", description: "Vanilla custard, caramelized sugar, fresh berries", price: 12, category: "Desserts", vegetarian: true },
  { name: "Tarte Tatin", description: "Upside-down caramelized apple tart, vanilla ice cream", price: 14, category: "Desserts", vegetarian: true },
  { name: "Chocolate Mousse", description: "Rich dark chocolate mousse, whipped cream", price: 11, category: "Desserts", vegetarian: true },
  { name: "Cheesecake", description: "New York style, berry compote", price: 13, category: "Desserts", vegetarian: true },
  { name: "Panna Cotta", description: "Silky Italian cream, raspberry coulis", price: 12, category: "Desserts", vegetarian: true },
  { name: "Sorbet Trio", description: "Three sorbet flavors, refreshing palate cleansers", price: 10, category: "Desserts", vegan: true },
  { name: "Profiteroles", description: "Cream puffs, chocolate sauce, whipped cream", price: 13, category: "Desserts", vegetarian: true },
  { name: "Flan", description: "Silky custard, caramel sauce", price: 11, category: "Desserts", vegetarian: true },
  { name: "Baked Alaska", description: "Meringue, ice cream, flambéed", price: 16, category: "Desserts", vegetarian: true },
  { name: "Millefeuille", description: "Layered puff pastry, cream, fruit", price: 14, category: "Desserts", vegetarian: true },
  { name: "Chocolate Torte", description: "Dense dark chocolate cake, ganache", price: 13, category: "Desserts", vegetarian: true },
  { name: "Sticky Toffee Pudding", description: "Moist sponge, toffee sauce, ice cream", price: 12, category: "Desserts", vegetarian: true },
  { name: "Soufflé Grand Marnier", description: "Light orange soufflé, powdered sugar", price: 16, category: "Desserts", vegetarian: true },
  { name: "Chocolate Eclairs", description: "Choux pastry, chocolate cream, ganache glaze", price: 11, category: "Desserts", vegetarian: true },
  { name: "Fruit Tart", description: "Pastry cream, seasonal fresh fruits", price: 13, category: "Desserts", vegetarian: true },
  { name: "Pistachio Gelato", description: "Creamy pistachio gelato, white chocolate", price: 9, category: "Desserts", vegetarian: true },
  { name: "Mille Feuille Strawberry", description: "Pastry, cream, fresh strawberries", price: 12, category: "Desserts", vegetarian: true },
  { name: "Chocolate Soufflé", description: "Risen chocolate soufflé, vanilla sauce", price: 15, category: "Desserts", vegetarian: true },

  // Coming Soon Items (50+)
  { name: "Wagyu Beef Tartare", description: "Premium Japanese beef, quail egg, caviar", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Foie Gras Torchon", description: "Silky foie gras, brioche, black truffle", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "King Crab Legs", description: "Fresh Alaska king crab, drawn butter", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Uni Don", description: "Sea urchin over sushi rice", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "White Truffle Risotto", description: "Arborio rice, shaved white truffle", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Matsutake Mushroom Dish", description: "Japanese autumn mushrooms, delicate preparation", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Premium Bluefin Tuna", description: "Seared toro, soy, wasabi, microgreens", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Morel Mushroom Pasta", description: "Handmade pasta, spring morels, truffle", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Dry-Aged Duck Breast", description: "Perfectly aged, cherry gastrique", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Pigeon en Croûte", description: "Game bird in puff pastry, port wine", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Black Garlic Wagyu", description: "Wagyu with black garlic fermented sauce", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "White Miso Sea Bass", description: "Chilean sea bass, miso glaze, herbs", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Bone Marrow Flan", description: "Savory flan with roasted bone marrow", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Saffron Risotto with Scallops", description: "Premium saffron, diver scallops", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Venison Wellington", description: "Tender venison, mushroom duxelles, pastry", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Lobster Soufflé", description: "Light lobster soufflé with lobster sauce", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Black Cod Miso", description: "Miso-marinated black cod, crispy skin", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Aged Beef Tartare Tower", description: "Architectural presentation of premium tartare", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Truffle Noodles", description: "Hand-pulled noodles, truffle essence", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Quail Stuffed with Foie", description: "Roasted quail filled with foie gras", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Hamachi Jalapeño", description: "Spicy yellowtail, jalapeño, ponzu", price: 0, category: "Coming Soon", comingSoon: true, spicy: true },
  { name: "Soft Shell Crab Tempura", description: "Seasonal soft shell crab, tempura batter", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Langoustine Thermidor", description: "Elegant langoustine preparation", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Beef Cheek Bourguignon", description: "Braised beef cheeks, red wine reduction", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Dover Sole Meunière Supreme", description: "Enhanced classic Dover sole preparation", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Seared Foie Gras", description: "Pan-seared foie gras, reduction sauce", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Lobster Pasta Al Tartufo", description: "Fresh pasta with lobster and black truffle", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Japanese A5 Wagyu Strip", description: "Highest grade Japanese marbled beef", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "White Fish Crudo", description: "Seasonal white fish, citrus, herbs", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Mushroom Tasting Menu", description: "Five mushroom preparations", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Edible Flowers Salad", description: "Seasonal edible flowers, delicate dressing", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Grass-Fed Ribeye A5", description: "Premium grass-fed with wagyu marbling", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Spot Prawns with Uni", description: "Fresh spot prawns, sea urchin, herbs", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Dry-Aged Tomahawk", description: "Massive dry-aged steak experience", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Caviar Tasting", description: "Multiple caviar varieties with accompaniments", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Ostrich Steak", description: "Lean, tender ostrich meat, spiced", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Sable Fish with Yuzu", description: "Rich sable fish, yuzu kosho", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Truffle Egg Carbonara", description: "Premium take on classic pasta", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Heritage Pork Chop", description: "Rare heritage pork breed, aged 45 days", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Abalone with XO Sauce", description: "Premium abalone, XO sauce", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Flaming Cheese Saganaki", description: "Greek fried cheese, flambéed", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Matsutake Tempura", description: "Precious mushroom tempura, dashi", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Beef Liver with Onions", description: "Prime beef liver, caramelized onions", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Eel Unagi Don", description: "Glazed freshwater eel over rice", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Lamb Brain Tasting", description: "Delicate lamb brain preparation", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Geoduck Sashimi", description: "Ultra-rare sea cucumber, raw", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Soy Butter Scallops", description: "Perfectly seared with soy butter", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Pine-Smoked Duck", description: "Duck smoked with pine, aromatics", price: 0, category: "Coming Soon", comingSoon: true },
  { name: "Monkfish Liver Pâté", description: "Rare delicacy, sea urchin, toast", price: 0, category: "Coming Soon", comingSoon: true },
];
